# Generated by Django 3.0.5 on 2021-07-05 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catogery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('phone_no', models.BigIntegerField(blank=True, default=0)),
                ('pincode', models.BigIntegerField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('locality', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('landmark', models.CharField(blank=True, default='', max_length=100)),
                ('alt_no', models.BigIntegerField(blank=True, default=0)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/products')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RTIShoppingapp.Catogery')),
            ],
        ),
    ]
