# Generated by Django 3.2.5 on 2022-01-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTIShoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.FloatField(default=0),
        ),
    ]
